name: flutter_sandbox
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  local_auth: 2.1.6
  local_auth_ios: 1.1.1
  local_auth_android: 1.0.21
  flutter: 
    sdk: flutter
  pdf: ^3.10.1
  path_provider: ^2.0.14
  printing: ^5.10.3
  path_provider_android: ^2.0.25
  path_provider_ios: ^2.0.11

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

